### ISSUE TITLE
Error in fail: unable to download package index

### ISSUE THREAD

**Issue by blockjon-dd** [GoogleContainerTools/rules_distroless#69]
I'm trying out rules_distroless and have run into a blocker that I can't resolve on my own.

I've got this lock file:

```
version: 1

sources:
  - channel: bookworm main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z
  - channel: bookworm-updates main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z
  - channel: bookworm-security main
    url: https://snapshot-cloudflare.debian.org/archive/debian-security/20240401T030239Z

archs:
  - arm64

packages:
  - tzdata
  - bash
  - coreutils
  - curl
  - lsb-release
  - zip
  - grep
  - gawk
  - libstdc++6
  - zlib1g
  - libncurses5
  - libncursesw5
  - ncurses-term
  - vim
```

Later, when I try to run the lock command:
```
bazel run @bookworm//:lock --verbose_failures
```
... I get this:

```
% bazel run @bookworm//:lock --verbose_failures
WARNING: Download from https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z/dists/bookworm-updates/main/binary-arm64/Packages.gz failed: class java.io.FileNotFoundException GET returned 404 NOT FOUND
INFO: Repository bookworm_resolution instantiated at:
  /Users/jon.block/Projects/dd/WORKSPACE.bzlmod:33:10: in <toplevel>
  /private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/rules_distroless/apt/index.bzl:80:17: in deb_index
Repository rule deb_resolve defined at:
  /private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/rules_distroless/apt/private/resolve.bzl:134:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bookworm_resolution':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/rules_distroless/apt/private/resolve.bzl", line 74, column 33, in _deb_resolve_impl
		pkgindex = package_index.new(rctx, sources = sources, archs = manifest["archs"])
	File "/private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/rules_distroless/apt/private/package_index.bzl", line 95, column 47, in _create
		(output, _) = _fetch_package_index(rctx, url, dist, comp, arch, "")
	File "/private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/rules_distroless/apt/private/package_index.bzl", line 27, column 13, in _fetch_package_index
		fail("unable to download package index")
Error in fail: unable to download package index
ERROR: no such package '@@bookworm_resolution//': unable to download package index
ERROR: /private/var/tmp/_bazel_jon.block/00f24a394e04e86cf755a9ff116729b1/external/bookworm/BUILD.bazel:2:6: @@bookworm//:lock depends on @@bookworm_resolution//:lock in repository @@bookworm_resolution which failed to fetch. no such package '@@bookworm_resolution//': unable to download package index
ERROR: Analysis of target '@@bookworm//:lock' failed; build aborted: Analysis failed
INFO: Elapsed time: 21.624s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

My guess its that its barfing on a 404 from this file:
https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z/dists/bookworm-updates/main/binary-arm64/Packages.gz

Am I doing something wrong? I'm calling this from a Mac running an M3 processor, in case that somehow makes a difference. 

bazel: 7.2.1
rules_distroless: 0.3.4

**Comment by blockjon-dd** [comment]
Admittedly I don't know that much about debian bookworm packaging, but I do notice that bookworm might have gotten rid of the Packages.gz option and so this would need to rely on the Packages.xz option.  I suspect there might be something wrong with these Bazel functions that try to use the xz file.

**Comment by blockjon-dd** [comment]
I root caused it - the env in which I'm running this didn't have the `xz` utility. I did a `brew install xz` and the problem is now resolved.
